### ISSUE TITLE
How can I check if the client can't join/if the server oid is wrong?

### ISSUE THREAD

**Issue by Ughuuu** [foxssake/netfox#147]
Right now if I try to do a `connect_nat` for eg, I get a `on_connect_nat` if successful, same for relay. But I don't get any even if it's not successful. Should I wait some time for when it times out?(Not sure what is the default timeout for this, maybe 10s but that seems like a lot), or how should this case be handled?

**Comment by elementbound** [comment]
In short, yes, a timeout is your best bet. In case of failure, noray silently ignores them.

Also, noray's protocol doesn't have a concept of replies, only commands. So the best we can do with that is for noray to send an error command in response, for which the integration can fire a signal.
