### ISSUE TITLE
Latency simulation

### ISSUE THREAD

**Issue by nicolagianelli** [foxssake/netfox#167]
Hello,
first of all, thank you for this plugin!
I played around with your examples and I'm going to try out your plugin before using it for my actual project, while playing around I saw it's missing an option to simulate latency and it could be good to have this option for testing purpose.

Thanks

**Comment by elementbound** [comment]
Hi,

This was considered during development. Unfortunately, I'm not sure if/how this can be done with Godot, so for now I use a [shell script] to set artificial latency.

I understand this won't work for everyone, as the script is Linux-only, so if something similar is available for Windows, I'm happy to add it to the repo!

[shell script]: https://github.com/foxssake/netfox/blob/main/sh/latency.sh

**Comment by nicolagianelli** [comment]
> Hi,
> 
> This was considered during development. Unfortunately, I'm not sure if/how this can be done with Godot, so for now I use a [shell script](https://github.com/foxssake/netfox/blob/main/sh/latency.sh) to set artificial latency. I think [MultiplayerPeerExtension](https://docs.godotengine.org/en/stable/classes/class_multiplayerpeerextension.html) is a good candidate, but I haven't tried writing GDExtensions yet.
> 
> I understand this won't work for everyone, as the script is Linux-only, so if something similar is available for Windows, I'm happy to add it to the repo!

Yea, I know there are methods to simulate latency at system level but it could be good to simulate it on in-game instances, so we could play multiple instances (in editor) and set different latency.
Anyway, if it's not straight forward and it's needed a GDExtension, I will try to do it and if I find a way I'll open a PR.
