### ISSUE TITLE
Inquiry about Support for Authoritative Client-Server Architecture buy running a Headless Godot Server (A game build runs on the server)

### ISSUE THREAD

**Issue by AmirDotDev0** [foxssake/netfox#209]
Hello Netfox devs,

First of all, I want to express my gratitude for your work on the Netfox addon for Godot. It's been an invaluable tool for many developers, including myself, in creating multiplayer games.

I've been exploring the capabilities of the Netfox addon, particularly in terms of networking architectures for multiplayer games. The example provided in the repo demonstrates how to set up multiplayer using LAN and Relay through Noray, which is fantastic for getting started with networked games, but I want to build my game using authoritative client-server architecture by making separate builds, a client build, which is the game that users will download and a server build where I'll run on the server, I'm wondering if Netfox supports this.

I appreciate any insights or information regarding this matter.

**Comment by elementbound** [comment]
Hi @AmirDotDev0,

I haven't experimented with headless builds yet, but this should be easily doable. You need your build to automatically start hosting on a given port, run it on a machine that can be accessed from the internet on said port, and it should work.

So in summary, this should be doable, the same way as with any other multiplayer game.

Hope you can build something cool with netfox, let me know if you have any further questions!

**Comment by AmirDotDev0** [comment]
Thanks for clarifying, so, basically it's not different from the built-in networking solution, regarding authoritative server implementation, that's good to know.
