### ISSUE TITLE
Use `node.get_indexed()` instead of `node.get()` for state and input properties

### ISSUE THREAD

**Issue by Protowalker** [foxssake/netfox#216]
Currently you can't use nested property access (the example I ran into for my game was `InputController:jump:packed`); the only change necessary to support this would be to call `node.get_indexed` and `node.set_indexed` instead of the current `node.get` and `node.set` inside of `property-entry.gd`:   
https://github.com/foxssake/netfox/blob/296bd3d5441ea71a5e39a9f43628411f2b3e7f30/addons/netfox/properties/property-entry.gd#L9

I'm not sure if this was a deliberate choice, maybe for performance, but I've made the change in my game and haven't had issues so far.

**Comment by elementbound** [comment]
That's a good catch, thanks! I wasn't aware of `get_indexed`, but now we have nested property support!
