### ISSUE TITLE
after_tick.emit runs before the tick

### ISSUE THREAD

**Issue by TheYellowArchitect** [foxssake/netfox#233]
https://github.com/foxssake/netfox/blob/c97141761bc307c5387599c0232e313903acd243/addons/netfox/network-time.gd#L402

Shouldn't `after_tick.emit()` be _below_ the tick increment? Otherwise, there is no reason to not use `on_tick.emit()`

**Comment by elementbound** [comment]
You can think of it in terms of semantics - the after_tick event emits the tick number we've just finished, instead of the tick number we'll be running during the next iteration.

**Comment by TheYellowArchitect** [comment]
Alright. Not an important problem since it can be moved in the code by the user (NetworkTime.gd), but just had to bring it up because of the word (after_tick) for a new user
(also changing it would be breaking compatibility but anyway)
