### ISSUE TITLE
Spammy console errors at Godot 4.3 (Forest Brawler Demo)

### ISSUE THREAD

**Issue by TheYellowArchitect** [foxssake/netfox#239]
![godot-4 3-error-spam](https://github.com/user-attachments/assets/168c65c8-46aa-43be-87be-d758c98d6331)

Not critical or anything, the animations play normally, but the console spam makes it impossible to find custom warnings (meshes need update), and ofc having no errors in console is ideal. Would be good for 1.8.1 release

**Comment by elementbound** [comment]
Forest Brawl uses Godot 4.1; netfox also uses Godot 4.1, but is compatible with 4.x

The surface format was changed IIRC around Godot 4.2, hence the warnings. There was also a rewrite introducing AnimationMixer, I strongly suspect the errors are related to that.

Opening Forest Brawl in a Godot version other than its supported 4.1 and getting warnings is not considered a bug. Closing as wontfix.

**Comment by TheYellowArchitect** [comment]
Understandable, because forest brawl on 4.3 should cause problems for 4.1 users.
Regardless, there should be on Readme.md that forest brawl demo works exclusively up to 4.1, otherwise they will be dissapointed/confused (e.g. thinking netfox won't work for 4.3 projects)
