### ISSUE TITLE
Settings have no tooltip/explanation

### ISSUE THREAD

**Issue by TheYellowArchitect** [foxssake/netfox#244]
Events: Enabled on/off, no tooltip, idk what this does
Same for others like display offset (int), input redundancy (int), recalibrate threshold (int)

It would be great to include a description for all of them. `hint_string` doesn't work

P.S. Bless you for having these, in the perfect location too instead of touching code

**Comment by elementbound** [comment]
Looked into this because I also needed it in #314, but I don't really see any API to add tooltips to custom project settings. I'll be on the lookout, but if this indeed can't be done, I'll have to close this issue and return to it later once it's doable.

**Comment by elementbound** [comment]
Just found the relevant proposal. Closing this issue until there's a way to register documentation for custom project settings.
