### ISSUE TITLE
avatar state should synchronize the property `Position` and `Quaternion`, instead of `Transform3D`

### ISSUE THREAD

**Issue by TheYellowArchitect** [foxssake/netfox#258]
`Transform3D` also contains `scale (Vector3)` which is needless. Also it is bloat for bandwidth (especially for serialization, `Transform3D` is 48 bytes!)

**Comment by elementbound** [comment]
For an example game, I want to keep it intuitive, syncing the player's whole transform, instead of settling for the 28 bytes of position + quaternion :) 

But otherwise I agree, it's best practice to only sync what you need.

Closing as won't fix.
