### ISSUE TITLE
Reconcillation math explanation

### ISSUE THREAD

**Issue by TheYellowArchitect** [foxssake/netfox#275]
I was reading this function of `NetworkWeapon`
```gdscript
## Override this method to reconcile the initial local and remote projectile
## state.
##
## Let's say the projectile travels in a straight line from its origin, but we
## receive a different origin from the server. In this reconciliation step, 
## the projectile's position can be adjusted to account for the different origin.
##
## Unless the use case is niche, the best practice is to consider the server's
## state as authorative.
func _reconcile(projectile: Node3D, local_data: Dictionary, remote_data: Dictionary):
	var local_transform = local_data["global_transform"] as Transform3D
	var remote_transform = remote_data["global_transform"] as Transform3D

	var relative_transform = projectile.global_transform * local_transform.inverse()
	var final_transform = remote_transform * relative_transform
	
	projectile.global_transform = final_transform
```
and I see the docs https://foxssake.github.io/netfox/netfox.extras/guides/network-weapon/ which explains reconcillation but not why the above Transform3D code works
I don't want to override it and write my own reconcillation, just curiosity why/how the above works.
Even a youtube link would suffice

**Comment by albertok** [comment]
It's simply trying to find a middle ground between where the server says the projectile is and where the local client has predicted so far. The local client is probably a little ahead.

The default code was a little off when I used it, I override  with the following:

```swift
func _reconcile(prj: Node3D, local_data: Dictionary, remote_data: Dictionary):
	var local_transform = local_data["global_transform"] as Transform3D
	var remote_transform = remote_data["global_transform"] as Transform3D

	var weight = 0.5  # reconciles halfway between local and remote. higher values favor remote.
	var final_transform = local_transform.interpolate_with(remote_transform, weight)

	prj.global_transform = final_transform
```

**Comment by TheYellowArchitect** [comment]
Thank you for sharing the above. A simple 0.5 lerp is crystal clear. I genuinely have no idea about transform math (e.g. how can you multiply such a matrix with an inverted transform, what is even inversion on a transform) so I am thankful for you sharing a simpler example which is also functional :yellow_heart: 

Btw, on "the default code was a little off" this sounds like a bug worthy of an issue if true, surely worth it given the solution is far easier to read
