### ISSUE TITLE
Animation Error occurs on project open

### ISSUE THREAD

**Issue by ValorZard** [foxssake/netfox#289]
Godot versions: 4.3 (Windows)
E 0:00:05:0577   _update_caches: AnimationMixer (at: powerup.tscn): 'powerup-float', Value Track:  'crateItem:position:x' must have at least one key to cache for blending.
  <C++ Error>    Condition "anim->track_get_key_count(i) == 0" is true. Continuing.
  <C++ Source>   scene/animation/animation_mixer.cpp:678 @ _update_caches()

**Comment by TheYellowArchitect** [comment]
Use Godot 4.1 for forest-brawl. 4.3 has broken compatibility with earlier versions.
As for netfox, its usable at any version (except 4.4 dev2 because that godot version has broken RPCs)

**Comment by elementbound** [comment]
Hey @ValorZard, @TheYellowArchitect is right - netfox supports any 4.x version, while Forest Brawl is written against 4.1. 

I'll close this issue after documenting version compatibility in the README.

**Comment by elementbound** [comment]
Updated docs, closing issue.
