### ISSUE TITLE
Some State Packets are not received

### ISSUE THREAD

**Issue by TheYellowArchitect** [foxssake/netfox#300]
### Description

**Some state ticks via `_submit_state` RPC are not received at all**. This is packet loss.
I will look deeper into this, but it seems serious enough to report it from now.
I even tried to switch internet lines (I have a landline and a satellite line) to confirm its not my internet to blame, but both cannot have packet losses, especially the landline.

**UPDATE**: This packet loss is caused by godotengine even in localhost without any internet connected. See the reply, skip this OP.

### Steps to reproduce

It already happens in forest brawl by default, no steps required to reproduce it. Aside of RNG to trigger it, as it takes a few boots to get a client to trigger it.

As for confirming this bug, inside `RollbackSynchronizer.gd`, add the following debug prints:
1. Inside the function `_submit_state`, right at the start:

```gdscript
if (root.player_id == 1):
	_logger.info("Client received tick %s for brawler 1" % tick)
	if (_states.has(tick - 1) == false):
		_logger.warning("non-linear states for brawler 1. Received tick %s while latest tick is %s" % [tick, _latest_state])
```
2. Replace `_record_tick` with this:

```gdscript
func _record_tick(tick: int):
	# Broadcast state we own
	if not _auth_state_props.is_empty():
		var broadcast = {}

		if (multiplayer.is_server() && tick < 500 && root.player_id == 1):
			_logger.info("recorded tick %s for brawler 1" % tick)

		for property in _auth_state_props:
			if _can_simulate(property.node, tick - 1):
				# Only broadcast if we've simulated the node
				broadcast[property.to_string()] = property.get_value()
	
		if broadcast.size() > 0:
			_latest_state = max(_latest_state, tick)
			_states[tick] = PropertySnapshot.merge(_states.get(tick, {}), broadcast)
			
			for picked_peer_id in multiplayer.get_peers():
				
				#if (NetworkTime._synced_clients.has(picked_peer_id) == false):
					#_logger.warning("At tick %s skipped peer id %s" % [tick, picked_peer_id])
					#continue

				# Broadcast as new state
				if (tick < 500 && root.player_id == 1):
					_logger.info("Sent state to player %s of brawler 1 for tick %s" % [picked_peer_id, tick])
				_submit_state.rpc_id(picked_peer_id, broadcast, tick)
		else:
			if (tick < 500 && root.player_id == 1):
				_logger.info("Empty broadcast for tick %s of brawler 1" % [tick])
```

`tick < 500` is for no spam at console, as this bug usually happens at the first seconds once a player has joined.

The commented out
```gdscript
#if (NetworkTime._synced_clients.has(picked_peer_id) == false):
	#_logger.warning("At tick %s skipped peer id %s" % [tick, picked_peer_id])
	#continue
```
is because I suspected that on the initial tick synchronization there may be problems, so ticks before time is synced may be wrong. But it doesn't matter whether its commented or not. These state packets lost are not before the time sync...
See: ![netfox-non-linear-bugg](https://github.com/user-attachments/assets/af5e327c-bb1e-4750-a3e7-e4f1750b164d)

In another try, in the image below, I show that tick 132 is straight up not received at all. And so the client goes from tick 131 to 133.
![netfox-missing-tick-132](https://github.com/user-attachments/assets/1da9c9b6-7da1-4e48-b7c1-ac4cf4edaf99)

I also managed to replicate this in the simple multiplayer example with the capsule players and box playable enviroment, the only change I had to do is create `var player_id: int` for the player, and set its value at `PlayerSpawner`, both exactly done like the brawler's in forest-brawl.
Though interestingly, it took way more tries to replicate for the first time (around 15) than forest brawl's 2~3.

![multiplayer-simple](https://github.com/user-attachments/assets/7827d136-8027-44a3-95f7-cca2945e327b)

### Notes
I tried testing https://github.com/foxssake/netfox/pull/284 for this bug, because it fixes inputs, in hopes inputs would somehow affect states. It didn't fix this bug (as expected)

My suspicion befell `rpc_id`, so I tried using `rpc` as forest-brawl does by default.
So I replaced `record_tick` with this:
```gdscript
func _record_tick(tick: int):
	# Record state for specified tick ( current + 1 )
	if not _record_state_props.is_empty() and tick > _latest_state:
		_states[tick] = PropertySnapshot.extract(_record_state_props)
		
	# Broadcast state we own
	if not _auth_state_props.is_empty():
		var broadcast = {}

		if (multiplayer.is_server() && tick < 500 && root.player_id == 1):
			_logger.info("recorded tick %s for brawler 1" % tick)

		for property in _auth_state_props:
			if _can_simulate(property.node, tick - 1):
				# Only broadcast if we've simulated the node
				broadcast[property.to_string()] = property.get_value()
	
		if broadcast.size() > 0:
			_latest_state = max(_latest_state, tick)
			_states[tick] = PropertySnapshot.merge(_states.get(tick, {}), broadcast)
			
			if (tick < 500 && root.player_id == 1 && multiplayer.get_peers().size() == 1):
				_logger.info("Sent state to player %s of brawler 1 for tick %s" % [multiplayer.get_peers()[0], tick])
			# Broadcast as new state
			_submit_state.rpc(broadcast, tick)
				
		else:
			if (tick < 500 && root.player_id == 1):
				_logger.info("Empty broadcast for tick %s of brawler 1" % [tick])
```

and ofc tested with only the server and 1 client. The bug still reproduces.

Btw for solving this - even if its a godot engine bug - netfox isn't currently designed to deal with packet loss. Which can happen in practical scenarios because of `unreliable_ordered` which uses UDP. The solution is quite simple: Once a tick is received, but the previous one(s) is not, the previous one(s) gets the value of the previous. Basically all the ticks in between, get the same value as the previous state. So for example, if you are at tick 32, and received tick 34, then the state of tick 33 gets the same value as the state of tick 32.
In #278 this fix is implemented.

### Versions

* Godot version: 4.1, 4.3, 4.4dev3
* netfox version: latest/master

**Comment by TheYellowArchitect** [comment]
I made a MRP for godotengine, and turns out that very rarely there is packet loss even in localhost with UDP. 

https://github.com/user-attachments/assets/1d55be09-7193-477e-87f2-9d7c8cccc00c

So this isn't caused by netfox. It's either "normal" behaviour or a godot engine bug (I will open an issue there to confirm)
That said, as mentioned earlier:

>netfox isn't currently designed to deal with packet loss. Which can happen in practical scenarios because of unreliable_ordered which uses UDP. The solution is quite simple: Once a tick is received, but the previous one(s) is not, the previous one(s) gets the value of the previous. Basically all the ticks in between, get the same value as the previous state. So for example, if you are at tick 32, and received tick 34, then the state of tick 33 gets the same value as the state of tick 32.
In https://github.com/foxssake/netfox/pull/278 this fix is implemented.

so to close this issue, packet loss must be taken in mind for states (inputs have `input_redundancy`)

**Comment by elementbound** [comment]
This is not a bug, this is how networks function. I also suggest against opening a Godot engine bug for this. 

To clarify, saying that this happens because of the `unreliable_ordered` channel using UDP is the wrong way to put it. *All channels* use UDP if the underlying connection uses UDP. Since the examples use ENET, every channel is transmitted through UDP, even `reliable`. 

> netfox isn't currently designed to deal with packet loss

This is false. The whole idea behind sending state over `unreliable_ordered` is that we don't care if some states are lost. States are sent continuously, so even if some packets are lost, the next ones should arrive. We also don't need a contiguous buffer of states on clients, since we don't resimulate ticks where we have the true state from the server, there's no point in doing that. 

> so to close this issue, packet loss must be handled properly in _submit_state

No, it doesn't need to be handled.

---

So, to clarify, **this is not a netfox bug, this is not a Godot bug, this is how networks operate.**

The things about using ENET and UDP is described well in the Godot docs, so once again, I suggest giving them a read.

**Comment by TheYellowArchitect** [comment]
>We also don't need a contiguous buffer of states on clients, since we don't resimulate ticks where we have the true state from the server, there's no point in doing that.

If the server sends a state to a client, and the client misses 2 states in a row, netfox will not crash, but there should be jitter.
(I haven't tested this)
