### ISSUE TITLE
Logger levels not working

### ISSUE THREAD

**Issue by TheYellowArchitect** [foxssake/netfox#330]
### :bug: Description

The console output is filled with messages (implemented in https://github.com/foxssake/netfox/pull/314 ) of level TRC aka trace.
By changing these 2 `_logger.trace()` functions to `_logger.info()`, and having my log level to DBG aka debug, I expected to not see these messages. Yet they appear.

Specifically in the following function

```gdscript
func _check_log_level(level: int) -> bool:
	var cmp_level = log_level
	if level < cmp_level:
		return false
	
	if module_log_level.has(module):
		var module_level = module_log_level.get(module)
		return level >= module_level
	
	return true
```

log_level is always 0, regardless of what log level is chosen at project settings. Where is `log_level` assigned? In the following codeblock

```gdscript
static func _static_init():
	log_level = ProjectSettings.get_setting("netfox/logging/log_level", LOG_MIN)
	module_log_level = {
		"netfox": ProjectSettings.get_setting("netfox/logging/netfox_log_level", LOG_MIN),
		"netfox.noray": ProjectSettings.get_setting("netfox/logging/netfox_noray_log_level", LOG_MIN),
		"netfox.extras": ProjectSettings.get_setting("netfox/logging/netfox_extras_log_level", LOG_MIN)
	}
``` 

note that it FAILED to get the log_level setting (returned null), so it went for the minimum aka `LOG_MIN`

### Steps to reproduce

1. Start forest-brawl
2. Connect with a client
3. Observe the console output

### Expected behavior

With my default Logger project settings (DBG), it shouldn't show the above theta logs.

### Observed behavior

All theta logs are shown.

### Versions

* Godot version: 4.1 stable
* netfox version: master

**Comment by elementbound** [comment]
Fixed, see #333 for more details on the issue.
